<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Godex.App</RootNamespace>
    <AssemblyName>Godex.App</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Godex.Core\Godex.Core.csproj" />
    <ProjectReference Include="..\Godex.Excel\Godex.Excel.csproj" />
    <ProjectReference Include="..\Godex.Ezpl\Godex.Ezpl.csproj" />
    <ProjectReference Include="..\Godex.Printing\Godex.Printing.csproj" />
  </ItemGroup>

</Project>
